name: sync_databricks_workflows
on:
  push:
    branches:
      - main

jobs:
  sync_jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Instalando Requeriments
        working-directory: src/04.workflows
        run: pip install -r requirements.txt
      - name: Sync dos Jobs
        env:
          DATABRICKS_WORKSPACE_URL: ${{ secrets.DATABRICKS_WORKSPACE_URL }}
          DATABRICKS_WORKSPACE_TOKEN: ${{ secrets.DATABRICKS_WORKSPACE_TOKEN }}
        working-directory: src/04.workflows
        run: python sync_jobs.py