name: sync_databricks_workflows
on:
  push:
    branches:
      - main

jobs:
  sync_jobs:
    runs-on: ubuntu-latest
    steps:
      working-directory: src/04.workflows
      - run: pip install -r requeriments.py
      - run: python sync_jobs.py